#################
## libraries ####
#################
library("optparse")
library("ukbtools")
library("ggplot2")


#################################
## parameters and input data ####
#################################
option_list <- list(
    make_option(c("-hs", "--HapMapSamples"), action="store",
                dest="HapMapSamples",
                type="character", help="Path to file with HapMap samples
                [default: %default].",
                default="~/data/hmeyer/HapMap/HapMap_PopulationCode.txt"),
    make_option(c("-hc", "--HapMapColors"), action="store",
                dest="HapMapColors",
                type="character", help="Path to file with HapMap sample colors
                [default: %default].",
                default="~/data/hmeyer/HapMap/HapMap_PopulationColors.txt"),
    make_option(c("-d", "--directory"), action="store", dest="directory",
               type="character", help="Path to output directory [default:
               %default].", default=NULL),
    make_option(c("-p", "--pcadata"), action="store", dest="pcadata",
               type="character", help="Path to pca output file generated by
               flashpca [default: %default].", default=NULL),
    make_option(c("-s", "--samples"), action="store", dest="samples",
               type="character", help="Path to study sample files (without hapmap
               samples [default: %default].", default=NULL),
    make_option(c("-n", "--name"), action="store", dest="name",
               type="character", help="Name of study sample files (for plotting)
               [default: %default].", default="UKBB"),
    make_option(c("-sc", "--samplesColor"), action="store", dest="samplesColor",
               type="character", help="Color for study samples (for plotting)
               [default: %default].", default="#2c7bb6")
)

args <- parse_args(OptionParser(option_list=option_list))

if (FALSE) {
    args <- list()
    args$pheno <- "~/data/ukbb/ukb-hrt/rawdata/FD.csv"
    args$rawdir <- "~/data/ukbb/ukb-hrt/rawdata"
    args$outdir <- "~/data/ukbb/ukb-hrt/phenotypes"
}

### ukb files converted via ukb_tools: http://biobank.ctsu.ox.ac.uk/showcase/docs/UsingUKBData.pdf
# ukb_unpack ukb22219.enc key
# ukb_conv ukb22219.enc_ukb r
# ukb_conv ukb22219.enc_ukb docs

# get rosetta error, but according to
# https://biobank.ctsu.ox.ac.uk/crystal/exinfo.cgi?src=faq#rosetta, nothing to
# worry about

################
## analysis ####
################

## Read data ####
dataFD <- data.table::fread(args$pheno, data.table=FALSE, stringsAsFactors=FALSE)

ukbb <- ukb_df(fileset="ukb22219", path=args$rawdir)
saveRDS(ukbb, paste(args$rawdir, "/ukb22219.rds", sep=""))

ukbb_fd <- dplyr::filter(ukbb, eid %in% dataFD$Folder)

## FD measurements of interest for association mapping
fd_measured_all <- dataFD[,33:37]
rownames(fd_measured_all) <- dataFD[, 1]
colnames(fd_measured_all) <- c("globalFD", "meanBasalFD", "meanApicalFD",
    "maxBasalFD", "maxApicalFD")
fd_na <- apply(fd_measured_all, 1,  function(x) any(is.na(x)))
fd_measured <- fd_measured_all[!fd_na, ]


## grep columns with covariates sex, age, bmi and weight ####
sex <- which(grepl("genetic_sex_", colnames(ukbb_fd)))
age <- which(grepl("age_when_attended_assessment_centre",
    colnames(ukbb_fd)))
bmi <- which(grepl("bmi_", colnames(ukbb_fd)))
weight <- which(grepl("^weight_", colnames(ukbb_fd)))


## manually check which columns are relevant and most complete ####
sexNA <- is.na(ukbb_fd[,sex]) # length(which(sexNA)) -> 467
allSex <- ukbb_fd[!sexNA,]

ageNA <- apply(ukbb_fd[!sexNA, age], 2, function(x) length(which(is.na(x)))) #0,14343,1171
weightNA <- apply(ukbb_fd[!sexNA, weight], 2, function(x) length(which(is.na(x)))) #28,14303,441
bmiNA <- apply(ukbb_fd[!sexNA, bmi] , 2, function(x) length(which(is.na(x)))) #32,14304,480

relevant <- c(sex, age[which.min(ageNA)], weight[which.min(weightNA)],
    bmi[which.min(bmiNA)])

covs <- allSex[, relevant]
covs$genetic_sex_f22001_0_0 <- as.numeric(covs$genetic_sex_f22001_0_0)
index_noNA <- which(apply(covs, 1, function(x) !any(is.na(x))))
covs_noNA <- covs[index_noNA,]
covs_noNA <- as.data.frame(apply(covs_noNA, 2, as.numeric))
rownames(covs_noNA) <- allSex$eid[index_noNA]

covs_noNA$height_f21002_comp <- sqrt(covs_noNA$weight_f21002_0_0/covs_noNA$body_mass_index_bmi_f21001_0_0)



fd_all <- merge(fd_measured, covs_noNA[,-4], by=0)
write.table(fd_all[,2:6], paste(args$outdir, "/FD_phenotypes.csv", sep=""),
    sep=",", row.names=fd_all$Row.names, col.names=NA, quote=FALSE)
write.table(fd_all[,7:10], paste(args$outdir, "/FD_covariates.csv", sep=""),
    sep=",", row.names=fd_all$Row.names, col.names=NA, quote=FALSE)
