##################
#### libraries ###
##################
library("optparse")

library (R.methodsS3)
library (R.oo)
library (R.utils)
library(sp)
#library(rgeos")
library(maptools)
library(scales)

###############
### program ###
###############

####################################
### 1. parameters and input data ###
####################################
option_list <- list(
    make_option(c("-hs", "--HapMapSamples"), action="store",
                dest="HapMapSamples",
                type="string", help="Path to file with HapMap samples
                [default: %default].",
                default="~/data/hmeyer/HapMap/HapMap_PopulationCode.txt"),
    make_option(c("-hc", "--HapMapColors"), action="store",
                dest="HapMapColors",
                type="string", help="Path to file with HapMap sample colors
                [default: %default].",
                default="~/data/hmeyer/HapMap/HapMap_PopulationColors.txt"),
    make_option(c("-d", "--directory"), action="store", dest="directory",
               type="string", help="Path to output directory [default:
               %default].", default="."),
    make_option(c("-p", "--pcadata"), action="store", dest="pcadata",
               type="string", help="Path to pca output file generated by
               flashpca [default: %default].", default=NULL),
    make_option(c("-s", "--samples"), action="store", dest="samples",
               type="string", help="Path to study sample files (without hapmap
               samples [default: %default].", default=NULL),
    make_option(c("-n", "--name"), action="store", dest="name",
               type="string", help="Name of study sample files (for plotting)
               [default: %default].", default=NULL),
    make_option(c("-sc", "--samplesColor"), action="store", dest="samplesColor",
               type="string", help="Color for study samples (for plotting)
               [default: %default].", default=NULL)
)
args <- parse_args(OptionParser(option_list=option_list))

if (interactive) {
    args <- list()
    args$HapMapColors <- "~/data/hmeyer/HapMap/HapMap_PopulationColors.txt"
    args$HapMapSamples <- "~/data/hmeyer/HapMap/HapMap_PopulationCode.txt"
    args$directory <- "~/data/ukbb/ukb-hrt/ancestry"
    args$pcadata <- paste(args$directory, "/",
                          "HapMapIII_CGRCh37.good_pos_ukb_imp_genome_v3_maf0.1",
                          ".pruned.merged_pca", sep="")
    args$samples <- paste(args$directory, "/",
                          "ukb_imp_genome_v3_maf0.1.pruned.intersection.",
                          "matched.fam", sep="")
    args$name <- "UKBB"
    args$samplesColor <- '#2c7bb6'
}

## Read data ####
samples <- data.table::fread(args$samples, header=FALSE, stringsAsFactors=FALSE,
    data.table=FALSE)
pca_data <- data.table::fread(args$pcadata, header=TRUE, stringsAsFactors=FALSE,
    data.table=FALSE)

pop_data <- read.table(args$HapMapSamples, header=TRUE, stringsAsFactors=FALSE)
pop_data_color <- read.table(args$HapMapColors, header=TRUE,
                             stringsAsFactors=FALSE)
pop_data <- merge(pop_data, pop_data_color, by="pop", all.X=TRUE)

## Reformat IDs of PCA file ####
samples_id <- pca_data[which(pca_data[,1] %in% samples[,1]),1]
samples_index <- which(pca_data[,1] %in% samples[,1])
pca_data[,1] <- paste(pca_data[,1],":", pca_data[,2], sep="")
pca_data <- pca_data[,-2]
pca_data[samples_index,1] <- samples_id
names(pca_data)[1] <- "ID"

## Combine pca data and population information ####
data_all <- merge(pca_data, pop_data, by="ID", all.x=TRUE)
data_all$pop[is.na(data_all$pop)] <- args$name
data_all$col[is.na(data_all$col)] <- args$samplesColor
data_all$pch[is.na(data_all$pch)] <- 24
data_all <- data_all[order(data_all$pop, decreasing=TRUE),]

## Find mean coordinates and distances of HapMap Europeans ####
all_european <- dplyr::filter(data_all, pop %in% c("CEU", "TSI"))
euro_pc1_mean <- mean(all_european$PC1)
euro_pc2_mean <- mean(all_european$PC2)

all_european$euclid_dist <- sqrt((all_european[,2] - euro_pc1_mean)^2 +
    (all_european[,3] - euro_pc2_mean)^2)

max_euclid_dist <- max(all_european$euclid_dist)

## Find samples' distances to HapMap Europeans ####
ukbb <- dplyr::filter(data_all, pop == args$name)
ukbb$euclid_dist <- sqrt((ukbb[,2] - euro_pc1_mean)^2 +
    (ukbb[,3] - euro_pc2_mean)^2)

euro_ukbb <- ukbb$ID[which(ukbb$euclid_dist < (max_euclid_dist * 1.5))]
not_euro_ukbb <- ukbb$ID[which(ukbb$euclid_dist > (max_euclid_dist * 1.5))]

## save sample lists ####
write.table(euro_ukbb, file=paste(args$dir, "/", "European_samples.csv", sep=""),
    sep=",", row.names=FALSE, col.names=FALSE)
write.table(not_euro_ukbb, file=paste(args$dir, "/", "NonEuropean_samples.csv",
    sep=""), sep=",", row.names=FALSE, col.names=FALSE)

## Plot distribution ####
plot(data_all[,2], data_all[,3],
     main=paste("PCA of HapMapIII populations and ukbb dataset"), 
     col=data_all$col, pch=".", xlab="PC1", ylab="PC2", xlim=c(-0.02,0.03), ylim=c(-0.02,0.03))
abline(v=euro_pc1_mean)
abline(h=euro_pc2_mean)
abline(v=euro_pc1_mean+max_euclid_dist1.5)
abline(v=euro_pc1_mean-max_euclid_dist1.5)
abline(h=euro_pc2_mean+max_euclid_dist1.5)
abline(h=euro_pc2_mean-max_euclid_dist1.5)
draw.circle(euro_pc1_mean, euro_pc2_mean, max_euclid_dist)
draw.circle(euro_pc1_mean, euro_pc2_mean, max_euclid_dist1.5)
draw.circle(euro_pc1_mean, euro_pc2_mean, ukbb$euclid_dist_bb[ukbb$euclid_dist_bb > max_euclid_dist1.5])
points(ukbb$euclid_dist_bb, ukbb$euclid_dist_bb)
points(ukbb[ukbb$euclid_dist_bb <= max_euclid_dist1.5,2], 
       ukbb[ukbb$euclid_dist_bb <= max_euclid_dist1.5,3], pch=".")
legend(-0.023,0.03, c(as.character(pop_dat_color$pop),"ukbb"), x.intersp=0.5, text.col=c(pop_dat_color$col,'#2c7bb6'), cex=0.7, pch=c(pop_dat_color$pch,24), col=c(pop_dat_color$col,'#2c7bb6'), box.lty = 0)

smoothScatter(data_all[,2], data_all[,3],
              col=data_all$col, xlab="PC1", ylab="PC2"   )
