#################
## libraries ####
#################
options(import.path=c("~/analysis/fractalgenetics",
                      "~/hannah/projects"))
options(bitmapType = 'cairo', device = 'pdf')


modules::import_package('ggplot2', attach=TRUE)
modules::import_package('GGally', attach=TRUE)
optparse <- modules::import_package('optparse')
ukbtools <- modules::import_package('ukbtools')
related <- modules::import('GWAS/relatedness')
autofd <- modules::import('fractal-analysis-processing')
smooth <- modules::import('utils/smoothAddR2')


#################################
## parameters and input data ####
#################################
option_list <- list(
    make_option(c("-u", "--ukbdir"), action="store", dest="rawdir",
               type="character", help="Path to ukb directory with decrypted ukb
               key.html file [default: %default].", default=NULL),
    make_option(c("-o", "--outdir"), action="store", dest="outdir",
               type="character", help="Path to output directory [default:
               %default].", default=NULL),
    make_option(c("-p", "--pheno"), action="store", dest="pheno",
               type="character", help="Path to fd phenotype file [default:
               %default].", default=NULL),
    make_option(c("-c", "--cov"), action="store", dest="cov",
               type="character", help="Path to LV volume covariate file
               [default: %default].", default=NULL),
    make_option(c("-i", "--interpolate"), action="store", dest="interpolate",
               type="integer", help="Number of slices to interpolate to
               [default: %default].", default=9),
    make_option(c("-s", "--samples"), action="store", dest="samples",
               type="character", help="Path to ukb genotype samples file
               [default: %default].", default=NULL),
    make_option(c("-r", "--relatedness"), action="store", dest="relatedness",
               type="character", help="Path to relatedness file generated by
               ukbgene rel [default: %default].", default=NULL),
    make_option(c("-e", "--europeans"), action="store", dest="europeans",
               type="character", help="Path to European samples file generated
               by ancestry.smk [default: %default].", default=NULL),
    make_option(c("-pcs", "--pcs"), action="store", dest="pcs",
               type="character", help="Path to pca output file generated by
               flashpca [default: %default].", default=NULL),
    optparse$make_option(c("--debug"), action="store_true",
               dest="debug", default=FALSE, type="logical",
               help="If set, predefined arguments are used to test the script
               [default: %default].")
)

args <- optparse$parse_args(OptionParser(option_list=option_list))

if (args$debug) {
    args <- list()
    args$outdir <- "~/data/digital-heart/phenotype/FD"
    args$pheno <- "~/data/digital-heart/phenotype/FD/20191709_DCM_FD_all.csv"
    args$interpolate <- 9
    args$cov <- "~/data/digital-heart/phenotype/2Dphenotype/20160705_GenScan.txt"
    args$samples <- "~/data/digital-heart/genotype/imputation/combined/genotypes/gencall.combined.clean.related.chr1.sample"
    args$europeans <- "~/data/digital-heart/genotype/QC/combined/DCM.gencall.combined.clean.related.fam"
    args$path2plink <- "/homes/hannah/bin/plink"
    args$genodir <- "~/data/digital-heart/genotype/QC/combined"
}

################
## analysis ####
################

## FD measurements ####
dataFD <- data.table::fread(args$pheno, data.table=FALSE,
                            stringsAsFactors=FALSE, na.strings=c("NA", "NaN"))
dataFD <- dataFD[!duplicated(dataFD$Folder),]

rownames(dataFD) <- dataFD[, 1]
colnames(dataFD)[colnames(dataFD) == 'FD - Slice 1'] <- 'Slice 1'
dataFD <- dataFD[,grepl("Slice \\d{1,2}", colnames(dataFD))]
colnames(dataFD) <- gsub(" ", "", colnames(dataFD))

# Exclude individuals where less than 6 slices were measured
NaN_values <- c("Sparse myocardium", "Meagre blood pool","FD measure failed")
fd_notNA <- apply(dataFD, 1,  function(x) {
                length(which(!(is.na(x) | x %in% NaN_values))) > 5
                            })
dataFD <- dataFD[fd_notNA, ]

# interpolate FD slice measures
FDi <- autofd$interpolate$fracDecimate(data=dataFD,
                                       interpNoSlices=args$interpolate,
                                       id.col.name='rownames')
# summary fd measurements
summaryFDi <- data.frame(t(apply(as.matrix(FDi), 1,
                                          autofd$stats$summaryStatistics,
                       discard=FALSE, sections="BMA")))

# plot distribution of FD along heart
FDalongHeart <- reshape2::melt(FDi, value.name = "FD")
colnames(FDalongHeart)[1:2] <- c("ID", "Slice")

FDalongHeart$Slice <- as.factor(as.numeric(gsub("Slice_", "",
                                                FDalongHeart$Slice)))
FDalongHeart$Location <- "Apical section"
FDalongHeart$Location[as.numeric(FDalongHeart$Slice) <= 3] <- "Basal section"
FDalongHeart$Location[as.numeric(FDalongHeart$Slice) <= 6 &
                      as.numeric(FDalongHeart$Slice) > 3] <- "Mid section"
FDalongHeart$Location <- factor(FDalongHeart$Location,
                                levels=c("Basal section", "Mid section",
                                         "Apical section"))

p_fd <- ggplot(data=FDalongHeart)
p_fd <- p_fd + geom_boxplot(aes(x=Slice, y=FD, color=Location)) +
    scale_color_manual(values=c('#67a9cf','#1c9099','#016c59')) +
    labs(x="Slice", y="FD") +
    theme_bw()

ggsave(plot=p_fd, file=paste(args$outdir, "/FDAlongHeart_DCM_slices",
                             args$interpolate, ".pdf", sep=""),
       height=4, width=4, units="in")



## Plot distribution of covariates ####
df <- dplyr::select(fd_all, MeanBasalFD, MeanMidFD, MeanApicalFD, LVEDV, SV, CO,
                    genetic_sex_f22001_0_0,
                    age_when_attended_assessment_centre_f21003_0_0,
                    weight_f21002_0_0,
                    body_mass_index_bmi_f21001_0_0, height_f21002_comp)
p <- ggpairs(df,
             upper = list(continuous = wrap("density", col="#b30000",
                                            size=0.1)),
             diag = list(continuous = wrap("densityDiag", size=0.4)),
             lower = list(continuous = wrap("smooth", alpha=0.5,size=0.1,
                                            pch=20),
                          combo = wrap("facethist")),
             columnLabels = c("meanBasalFD", "meanMidFD", "meanApicalFD",
                              "EDV~(ml)", "SV~(ml)", "CO~(ml/min)", "Sex~(f/m)",
                              "Age~(years)", "Height~(m)",
                              "Weight~(kg)", "BMI~(kg/m^2)"),
             labeller = 'label_parsed',
             axisLabels = "show") +
    theme_bw() +
    theme(panel.grid = element_blank(),
          axis.text = element_text(size=6),
          axis.text.x = element_text(angle=90),
          strip.text = element_text(size=8),
          strip.background = element_rect(fill="white", colour=NA))
p[6,5] <- p[6,5] + geom_histogram(binwidth=3)
ggsave(plot=p, file=paste(args$outdir, "/pairs_fdcovariates.png", sep=""),
       height=12, width=12, units="in")

df_small <- dplyr::select(fd_all,
                    genetic_sex_f22001_0_0,
                    age_when_attended_assessment_centre_f21003_0_0,
                    weight_f21002_0_0,
                    body_mass_index_bmi_f21001_0_0, height_f21002_comp,
                    SV, MeanGlobalFD)
p <- ggpairs(df_small,
             upper = list(continuous = wrap("smooth", alpha=0.5,size=0.1,
                                            pch=20),
                          combo = wrap("facethist")),
             diag = list(continuous = wrap("densityDiag", size=0.4)),
             lower = list(continuous = wrap("smooth", alpha=0.5,size=0.1,
                                            pch=20),
                          combo = wrap("facethist")),
             columnLabels = c("Sex~(f/m)",
                              "Age~(years)", "Height~(m)",
                              "Weight~(kg)", "BMI~(kg/m^2)", "SV~(ml)",
                              "global~FD"),
             labeller = 'label_parsed',
             axisLabels = "show") +
    theme_bw() +
    theme(panel.grid = element_blank(),
          axis.text = element_text(size=6),
          axis.text.x = element_text(angle=90),
          strip.text = element_text(size=8),
          strip.background = element_rect(fill="white", colour=NA))
ggsave(plot=p, file=paste(args$outdir, "/pairs_fdcovariates_small.pdf", sep=""),
       height=12, width=12, units="in")

