##################
#### libraries ###
##################
library("optparse")
library("ggplot2")
library("geomnet")

###############
### program ###
###############

####################################
### 1. parameters and input data ###
####################################
option_list <- list(
    make_option(c("-hs", "--HapMapSamples"), action="store",
                dest="HapMapSamples",
                type="character", help="Path to file with HapMap samples
                [default: %default].",
                default="~/data/hmeyer/HapMap/HapMap_PopulationCode.txt"),
    make_option(c("-hc", "--HapMapColors"), action="store",
                dest="HapMapColors",
                type="character", help="Path to file with HapMap sample colors
                [default: %default].",
                default="~/data/hmeyer/HapMap/HapMap_PopulationColors.txt"),
    make_option(c("-d", "--directory"), action="store", dest="directory",
               type="character", help="Path to output directory [default:
               %default].", default=NULL),
    make_option(c("-p", "--pcadata"), action="store", dest="pcadata",
               type="character", help="Path to pca output file generated by
               flashpca [default: %default].", default=NULL),
    make_option(c("-s", "--samples"), action="store", dest="samples",
               type="character", help="Path to study sample files (without hapmap
               samples [default: %default].", default=NULL),
    make_option(c("-n", "--name"), action="store", dest="name",
               type="character", help="Name of study sample files (for plotting)
               [default: %default].", default="UKBB"),
    make_option(c("-sc", "--samplesColor"), action="store", dest="samplesColor",
               type="character", help="Color for study samples (for plotting)
               [default: %default].", default="#2c7bb6")
)

args <- parse_args(OptionParser(option_list=option_list))

if (FALSE) {
    args <- list()
    args$HapMapColors <- "~/data/hmeyer/HapMap/HapMap_PopulationColors.txt"
    args$HapMapSamples <- "~/data/hmeyer/HapMap/HapMap_PopulationCode.txt"
    args$directory <- "~/data/ukbb/ukb-hrt/ancestry"
    args$pcadata <- paste(args$directory, "/",
                          "HapMapIII_CGRCh37.good_pos_ukb_imp_genome_v3_maf0.1",
                          ".pruned.merged_pca", sep="")
    args$samples <- paste(args$directory, "/",
                          "ukb_imp_genome_v3_maf0.1.pruned.intersection.",
                          "matched.fam", sep="")
    args$name <- "UKBB"
    args$samplesColor <- '#2c7bb6'
}

## Read data ####
samples <- data.table::fread(args$samples, header=FALSE, stringsAsFactors=FALSE,
    data.table=FALSE)
pca_data <- data.table::fread(args$pcadata, header=TRUE, stringsAsFactors=FALSE,
    data.table=FALSE)

pop_data <- read.table(args$HapMapSamples, header=TRUE, stringsAsFactors=FALSE)
pop_data_color <- read.table(args$HapMapColors, header=TRUE,
                             stringsAsFactors=FALSE)
pop_data <- merge(pop_data, pop_data_color, by="pop", all.X=TRUE)

## Reformat IDs of PCA file ####
samples_id <- pca_data[which(pca_data[,1] %in% samples[,1]),1]
samples_index <- which(pca_data[,1] %in% samples[,1])
pca_data[,1] <- paste(pca_data[,1],":", pca_data[,2], sep="")
pca_data <- pca_data[,-2]
pca_data[samples_index,1] <- samples_id
names(pca_data)[1] <- "ID"

## Combine pca data and population information ####
data_all <- merge(pca_data, pop_data, by="ID", all.x=TRUE)
data_all$pop[is.na(data_all$pop)] <- args$name
data_all$col[is.na(data_all$col)] <- args$samplesColor
data_all$pch[is.na(data_all$pch)] <- 24
data_all <- data_all[order(data_all$pop, decreasing=TRUE),]

pop_data_color <- rbind(pop_data_color,c(args$name, args$samplesColor, 24))
data_all$col <- as.factor(data_all$col)
data_all$pop <- factor(data_all$pop, levels=pop_data_color$pop)
data_all$pch <- as.factor(data_all$pch)

## Find mean coordinates and distances of HapMap Europeans ####
all_european <- dplyr::filter(data_all, pop %in% c("CEU", "TSI"))
euro_pc1_mean <- mean(all_european$PC1)
euro_pc2_mean <- mean(all_european$PC2)

all_european$euclid_dist <- sqrt((all_european[,2] - euro_pc1_mean)^2 +
    (all_european[,3] - euro_pc2_mean)^2)

max_euclid_dist <- max(all_european$euclid_dist)

## Find samples' distances to HapMap Europeans ####
ukbb <- dplyr::filter(data_all, pop == args$name)
ukbb$euclid_dist <- sqrt((ukbb[,2] - euro_pc1_mean)^2 +
    (ukbb[,3] - euro_pc2_mean)^2)

euro_ukbb <- ukbb$ID[which(ukbb$euclid_dist < (max_euclid_dist * 1.5))]
not_euro_ukbb <- ukbb$ID[which(ukbb$euclid_dist > (max_euclid_dist * 1.5))]

## save sample lists ####
write.table(euro_ukbb, file=paste(args$dir, "/", "European_samples.csv", sep=""),
    sep=",", row.names=FALSE, col.names=FALSE, quote=FALSE)
write.table(not_euro_ukbb, file=paste(args$dir, "/", "NonEuropean_samples.csv",
    sep=""), sep=",", row.names=FALSE, col.names=FALSE, quote=FALSE)

## Plot distribution ####
p <- ggplot()
p <- p + geom_point(data=data_all, aes(x=PC1, y=PC2, color=pop)) +
    scale_color_manual(values=pop_data_color$col, name="Population") +
    geom_circle(data=data.frame(x=euro_pc1_mean, y=euro_pc2_mean), 
                aes(x=x, y=y), linewidth=2, color="black",
                radius=(max_euclid_dist * 1.5)) +
    theme_bw()
ggsave(plot=p,
       file=paste(args$dir, "/", "HapMap_", args$name, "_pca.png", sep=""))
