#################
## libraries ####
#################
options(import.path=c("/homes/hannah/analysis/fractalgenetics",
                      "/homes/hannah/projects"))
options(bitmapType = 'cairo', device = 'pdf')

modules::import_package('ggplot2', attach=TRUE)
modules::import_package('dplyr', attach=TRUE)
optparse <- modules::import_package('optparse')
ukbtools <- modules::import_package('ukbtools')
related <- modules::import('GWAS/relatedness')
smooth <- modules::import('utils/smoothAddR2')


#################################
## parameters and input data ####
#################################
option_list <- list(
    make_option(c("-u", "--ukbdir"), action="store", dest="rawdir",
               type="character", help="Path to ukb directory with decrypted ukb
               key.html file [default: %default].", default=NULL),
    make_option(c("-o", "--outdir"), action="store", dest="outdir",
               type="character", help="Path to output directory [default:
               %default].", default=NULL),
    make_option(c("-p", "--pheno"), action="store", dest="pheno",
               type="character", help="Path to fd phenotype file [default:
               %default].", default=NULL),
    make_option(c("-c", "--cov"), action="store", dest="cov",
               type="character", help="Path to LV volume covariate file
               [default: %default].", default=NULL),
    make_option(c("-i", "--interpolate"), action="store", dest="interpolate",
               type="integer", help="Number of slices to interpolate to
               [default: %default].", default=9),
    make_option(c("-s", "--samples"), action="store", dest="samples",
               type="character", help="Path to ukb genotype samples file
               [default: %default].", default=NULL),
    make_option(c("-r", "--relatedness"), action="store", dest="relatedness",
               type="character", help="Path to relatedness file generated by
               ukbgene rel [default: %default].", default=NULL),
    make_option(c("-e", "--europeans"), action="store", dest="europeans",
               type="character", help="Path to European samples file generated
               by ancestry.smk [default: %default].", default=NULL),
    make_option(c("-pcs", "--pcs"), action="store", dest="pcs",
                ptions(import.path="/homes/hannah/GWAS/analysis/fd")
               type="character", help="Path to pca output file generated by
               flashpca [default: %default].", default=NULL),
    make_option(c("--debug"), action="store_true",
               dest="debug", default=FALSE, type="logical",
               help="If set, predefined arguments are used to test the script
               [default: %default].")
)

args <- optparse$parse_args(OptionParser(option_list=option_list))

if (args$debug) {
    args <- list()
    args$rawdir <- "~/data/ukbb/ukb-hrt/rawdata"
    args$outdir <- "~/data/ukbb/ukb-hrt/phenotypes/180628_fractal_dimension"
    args$pheno <- "~/data/ukbb/ukb-hrt/rawdata/180628_fractal_dimension.csv"
    args$interpolate <- 9
    args$cov <- "~/data/ukbb/ukb-hrt/rawdata/180628_cardiac_phenotypes.csv"
    args$samples <- "~/data/ukbb/ukb-hrt/rawdata/ukb40616_imp_chr1_v3_s487317.sample"
    args$relatedness <-"~/data/ukbb/ukb-hrt/rawdata/ukb40616_rel_s488282.dat"
}

## ukb phenotype files converted via ukb_tools:
# http://biobank.ctsu.ox.ac.uk/showcase/docs/UsingUKBData.pdf

############
## data ####
############


## ukbb bulk data ####
# ukbb phenotypes
if (! file.exists(aste(args$rawdir, "/ukb22219.rds", sep="")) {
    bb <- ukb_df(fileset="ukb22219", path=args$rawdir)
    saveRDS(bb, paste(args$rawdir, "/ukb22219.rds", sep=""))
} else {
    bb <- readRDS(paste(args$rawdir, "/ukb22219.rds", sep=""))
}


# ukbb genotype samples via ukbgene imp -c1 -m
samples <- data.table::fread(args$samples, data.table=FALSE, skip=2,
                             stringsAsFactors=FALSE,
                             col.names=c("ID_1", "ID_2", "missing", "sex"))

# ukbb relatedness file via ukbgene rel
relatedness <- data.table::fread(args$relatedness, data.table=FALSE,
                             stringsAsFactors=FALSE)

################
## analysis ####
################

# Get bulk data for all genotyped samples
bb_genotyped <- dplyr::filter(bb, f.eid %in% samples$ID_1)
saveRDS(bb_genotyped, paste(args$rawdir, "/ukb22219_genotyped.rds", sep=""))


# select covariates for case-control grs
# sample IDS
select_eid <- bb %>%
  select(starts_with("f.eid"))
colnames(select_eid) <- "eid"

# sex: genetic_sex_f22001_0_0
select_sex <- bb%>%
  select(starts_with("f.22001.0.0"))
colnames(select_sex) <- "sex"

# age: age_when_attended_assessment_centre_f21003_0_0
select_age <- bb%>%
  select(starts_with("f.21003.0.0"))
colnames(select_age) <- "age"

# weight: weight_f21002_0_0
select_weight <- bb%>%
  select(starts_with("f.21002.0.0"))
colnames(select_weight) <- "weight"

# bmi: body_mass_index_bmi_f21001_0_0
select_bmi <- bb%>%
  select(starts_with("f.21001.0.0"))
colnames(select_bmi) <- "bmi"

# genetic ethnic grouping: field 22006:
select_ethnicity <- bb%>%
  select(starts_with("f.22006"))
colnames(select_ethnicity) <- "ethnicity"

# genetic principal components: field 22009
select_pca <- bb%>%
  select(starts_with("f.22009"))
colnames(select_pca) <- paste("PC", 1:ncol(select_pca))

# genetic kinship to other participants: field 22021
select_kinship <- bb%>%
  select(starts_with("f.22021"))

# heart rate during PWA (proxy for MRI taken): field 12673
select_mri <- bb%>%
  select(starts_with("f.12673.2.0"))
colnames(select_mri) <- "mri_taken"


select_height <- data.frame(height=sqrt(select_weight$weight/select_bmi$bmi))

# combine all into one data.frame
covs_hf <- dplyr::bind_cols(select_eid, select_sex, select_age, select_weight,
                           select_bmi, select_height, select_pca)

# restrict to white british encoded as 1, NA for everything else (as this is
# the biggest subset) described here
# https://biobank.ctsu.ox.ac.uk/crystal/coding.cgi?id=1002
# restrict to people without MRI ie NA in the heart rate during PWA measurement

select_mri$keep <- 1
select_mri$keep[!is.na(select_mri$mri_taken)] <- NA
keep <- !is.na(select_mri$keep) & !is.na(select_ethnicity$ethnicity)

related_samples <- related$smartRelatednessFilter(covs_hf$eid[keep],
                                                  relatedness)
related2filter <- c(related_samples$related2filter,
                    related_samples$related2decide$ID1)

fd_norelated <- fd_all[!fd_all$Row.names %in% related2filter,]
