#################
## libraries ####
#################
options(bitmapType = 'cairo', device = 'pdf')

modules::import_package('dplyr', attach=TRUE)
optparse <- modules::import_package('optparse')


#################################
## parameters and input data ####
#################################
option_list <- list(
    make_option(c("-o", "--outdir"), action="store", dest="outdir",
               type="character", help="Path to ukb parent directory
               [default: %default].", default=NULL),
    make_option(c("-d", "--data"), action="store", dest="ukbdata",
               type="character", help="Path to ukb bulk tab-separated data file
               [default: %default].", default=NULL),
    make_option(c("-s", "--samples"), action="store", dest="samples",
               type="character", help="Path to ukb genotype samples file
               [default: %default].", default=NULL),
    make_option(c("-r", "--relatedness"), action="store", dest="relatedness",
               type="character", help="Path to relatedness file generated by
               ukbgene rel [default: %default].", default=NULL),
    make_option(c("--debug"), action="store_true",
               dest="debug", default=FALSE, type="logical",
               help="If set, predefined arguments are used to test the script
               [default: %default].")
)

args <- optparse$parse_args(OptionParser(option_list=option_list))

if (args$debug) {
    args <- list()
    args$outdir <- "~/data/ukbb/ukb-hrt/heart_failure_phenotypes"
    args$samples <- "~/data/ukbb/ukb-hrt/rawdata/ukb40616_imp_chr1_v3_s487317.sample"
    args$relatedness <- "~/data/ukbb/ukb-hrt/rawdata/ukb40616_rel_s488282.dat"
    args$ukbdata <- "~/data/ukbb/ukb-hrt/rawdata/ukb40616.txt"
}

## ukb phenotype files converted via ukb_tools:
# http://biobank.ctsu.ox.ac.uk/showcase/docs/UsingUKBData.pdf

############
## data ####
############


## ukbb bulk data ####
bb <- data.table$fread(args$ukbdata, header=TRUE, sep="\t", fill=TRUE)

# ukbb genotype samples via ukbgene imp -c1 -m
samples <- data.table::fread(args$samples, data.table=FALSE, skip=2,
                             stringsAsFactors=FALSE,
                             col.names=c("ID_1", "ID_2", "missing", "sex"))

# ukbb relatedness file via ukbgene rel
relatedness <- data.table::fread(args$relatedness, data.table=FALSE,
                             stringsAsFactors=FALSE)

################
## analysis ####
################

# select covariates for heart failure grs
# sample IDS
select_eid <- bb %>%
  select(starts_with("f.eid"))
colnames(select_eid) <- "eid"

# sex: genetic_sex_f22001_0_0
select_sex <- bb%>%
  select(starts_with("f.22001.0.0"))
colnames(select_sex) <- "sex"

# age: age_when_attended_assessment_centre_f21003_0_0
select_age <- bb%>%
  select(starts_with("f.21003.0.0"))
colnames(select_age) <- "age"

# weight: weight_f21002_0_0
select_weight <- bb%>%
  select(starts_with("f.21002.0.0"))
colnames(select_weight) <- "weight"

# bmi: body_mass_index_bmi_f21001_0_0
select_bmi <- bb%>%
  select(starts_with("f.21001.0.0"))
colnames(select_bmi) <- "bmi"

# genetic ethnic grouping: field 22006:
select_ethnicity <- bb%>%
  select(starts_with("f.22006"))
colnames(select_ethnicity) <- "ethnicity"

# genetic principal components: field 22009
select_pca <- bb%>%
  select(starts_with("f.22009"))
colnames(select_pca) <- paste("PC", 1:ncol(select_pca), sep="")

# genetic kinship to other participants: field 22021
select_kinship <- bb%>%
  select(starts_with("f.22021"))

# heart rate during PWA (proxy for MRI taken): field 12673
select_mri <- bb%>%
  select(starts_with("f.12673.2.0"))
colnames(select_mri) <- "mri_taken"


select_height <- data.frame(height=sqrt(select_weight$weight/select_bmi$bmi))

# combine all into one data.frame
covs_hf <- dplyr::bind_cols(select_eid, select_sex, select_age, select_weight,
                           select_bmi, select_height, select_pca)

# restrict to white british encoded as 1, NA for everything else (as this is
# the biggest subset) described here
# https://biobank.ctsu.ox.ac.uk/crystal/coding.cgi?id=1002
# restrict to people without MRI ie NA in the heart rate during PWA measurement

select_mri$keep <- 1
select_mri$keep[!is.na(select_mri$mri_taken)] <- NA
keep <- !is.na(select_mri$keep) & !is.na(select_ethnicity$ethnicity)
covs_hf <- covs_hf[keep,]

# get IDs of related samples
keepRelatedness <- dplyr::filter(relatedness,
                                 ID1 %in% covs_hf$eid | ID2 %in% covs_hf$eid)


relatedIDs <- plinkQC::relatednessFilter(relatedness=keepRelatedness,
                                         relatednessIID1="ID1",
                                         relatednessIID2="ID2",
                                         relatednessRelatedness="Kinship",
                                         relatednessTh=0.185)

relatedIDs$failIDs$IID <- as.character(relatedIDs$failIDs$IID)
write.table(relatedIDs$relatednessFails,
            file=file.path(args$outdir,
                           "heart_failure_related_samples_overview.csv"),
            sep=",", quote=FALSE, col.names=TRUE, row.names=FALSE)
write.table(relatedIDs$failIDs,
            file=file.path(args$outdir,
                           "heart_failure_related_samples_ids.csv"),
            sep=",", quote=FALSE, col.names=TRUE, row.names=FALSE)


covs_hf_norelated <- covs_hf[!covs_hf$eid %in% relatedIDs$failIDs$IID,]

overview_id <- list(all=select_eid$eid)
overview_id$mri_taken <- select_eid$eid[is.na(select_mri$keep)]
overview_id$nonwhitebritish <- select_eid$eid[is.na(select_ethnicity$ethnicity)]
overview_id$related <- relatedIDs$faiids
overview_id$all_filtered <- covs_hf_norelated$eid

overview <- data.frame(all=nrow(select_eid))
overview$mri_taken <- sum(is.na(select_mri$keep))
overview$nonwhitebritish <- sum(is.na(select_ethnicity$ethnicity))
overview$related <- length(relatedIDs$failIDs$IID)
overview$all_filtered <- nrow(covs_hf_norelated)

write.table(covs_hf_norelated, file=file.path(args$outdir,
                                              "heart_failure_covariates.csv"),
            sep=",", quote=FALSE, col.names=TRUE, row.names=FALSE)

write.table(overview, file=file.path(args$outdir,
                                     "heart_failure_samples_overview.csv"),
            sep=",", quote=FALSE, col.names=TRUE, row.names=FALSE)

saveRDS(overview_id, file=file.path(args$outdir,
                                    "heart_failure_samples_id.rds"))
